[package]
name = "bench-electron-addon"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bench-core = { path = "../../core" }
napi = { version = "3", default-features = false, features = ["napi9"] }
napi-derive = "3"
once_cell = "1"

[build-dependencies]
napi-build = "2"

[workspace]
